name:                plonk-constraints
version:             0.1.0.0
github:              "pacastega/plonk-constraints"
license:             GPL-3
author:              "Pablo Castellanos"
maintainer:          "p.cas.gar@gmail.com"
copyright:           "2024 Pablo Castellanos"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pacastega/plonk-constraints#readme>

dependencies:
- base >= 4.7 && < 5
- finite-field
- containers
- vector
- poly

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wno-missing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-top-binds
- -Wno-incomplete-patterns
- -XGADTs

library:
  source-dirs: src
  ghc-options:
    - -fplugin=LiquidHaskell
  dependencies:
    - liquidhaskell
    - liquidhaskell-boot
    - liquid-prelude
    - liquid-vector

executables:
  plonk-constraints-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=LiquidHaskell
    dependencies:
    - plonk-constraints
    - liquidhaskell
    - liquidhaskell-boot
    - liquid-prelude
    - liquid-vector
