# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: nightly-2024-06-04 # ghc-9.8.2

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
  - hashable-1.4.3.0
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: a6cdb9517db5166de80657ae08c6b9f3a0586b71 # 2024-06-04
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: ea23657696b16fed5042fc5db3a9d0f55aedf885 # 2024-05-30
  - finite-field-0.10.0

allow-newer: true
