# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: nightly-2024-06-04 # ghc-9.8.2

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
  - hashable-1.4.3.0
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: a6cdb9517db5166de80657ae08c6b9f3a0586b71 # 2024-06-04
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: ea23657696b16fed5042fc5db3a9d0f55aedf885 # 2024-05-30
  - finite-field-0.10.0

#  - /Users/niki.vazou/liquidtypes/liquidhaskell
#  - /Users/niki.vazou/liquidtypes/liquidhaskell/liquid-prelude
#  - /Users/niki.vazou/liquidtypes/liquidhaskell/liquid-vector
#  - /Users/niki.vazou/liquidtypes/liquidhaskell/liquidhaskell-boot
#  - /Users/niki.vazou/liquidtypes/liquidhaskell/liquid-fixpoint



allow-newer: true

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of Stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.15"
#
# Override the architecture used by Stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by Stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
